name: "mask_rg"

path_store_weights: "."
path_load_weights: "."
confidence_threshold: 0.75
mask_threshold: 0.75

train:
  dataset_path: "."
  images: "."
  masks: "."
  epochs: 20
  lr: 0.0001
  batch_size: 5
  backbone: resnet50
  backbone_pretrained: True
  cuda_available: False

test:
  path_test_image: "./test.png"
