name: "mask_rg"

path_store_weights: "/home/freiberg/shelf/"
path_load_weights: "/home/freiberg/shelf/rg_net_test.pth"
confidence_threshold: 0.75
mask_threshold: 0.75

train:
  store_model_each_epoch: False
  use_pretrained: True
  epochs: 3
  lr: 0.0001
  batch_size: 2
  backbone: resnet50
  backbone_pretrained: True
  cuda_available: False

dataset:
  dataset_path: "/home/freiberg/shelf/test-ds/"
  base_rgb: ""
  base_seg: "_seg"
  base_depth: "_depth"
  mask_dir: "mask/"
  depth_dir: "depth/"

test:
  path_test_image: "/home/freiberg/shelf/test.png"
