success_threshold: 0.8
change_threshold: 100
discount: 0.99
seed: 0
explore_probability: 0.1
amount_pushes: 10
path_load_weights: "/home/freiberg/shelf/dqn_net.pth"

train:
  maximum_iterations: 1000000
  lr: 0.0001
  gamma: 0.99
  use_cuda: True
  pretrained_weights: ""